USE [master]
GO

/****** Object:  Database [KustOnlinePortal]    Script Date: 4/16/2020 6:27:09 AM ******/
CREATE DATABASE [KustOnlinePortal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KustOnlinePortal', FILENAME = N'E:\DB\MSSQL15.MSSQLSERVER\MSSQL\DATA\KustOnlinePortal.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KustOnlinePortal_log', FILENAME = N'E:\DB\MSSQL15.MSSQLSERVER\MSSQL\DATA\KustOnlinePortal_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KustOnlinePortal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KustOnlinePortal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET ARITHABORT OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KustOnlinePortal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KustOnlinePortal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KustOnlinePortal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KustOnlinePortal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET RECOVERY FULL 
GO

ALTER DATABASE [KustOnlinePortal] SET  MULTI_USER 
GO

ALTER DATABASE [KustOnlinePortal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KustOnlinePortal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [KustOnlinePortal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [KustOnlinePortal] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [KustOnlinePortal] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [KustOnlinePortal] SET QUERY_STORE = OFF
GO

ALTER DATABASE [KustOnlinePortal] SET  READ_WRITE 
GO

