//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public string CNIC { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string Batch { get; set; }
        public string ContactNo { get; set; }
        public string EmergencyNo { get; set; }
        public string RegisrationNo { get; set; }
    
        public virtual Authentication Authentication { get; set; }
    }
}
