//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomsSeat
    {
        public string RoomCode { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Times { get; set; }
        public int SeatNo { get; set; }
        public string Paper { get; set; }
        public string RegisrationNo { get; set; }
        public string Faculty { get; set; }
    
        public virtual Authentication Authentication { get; set; }
    }
}
