//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public string CourseCode { get; set; }
        public string CourseTitle { get; set; }
        public int Semester { get; set; }
        public string RegisrationNo { get; set; }
    
        public virtual Authentication Authentication { get; set; }
    }
}
