//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamAttendance
    {
        public int ID { get; set; }
        public string CourseCode { get; set; }
        public string CourseTitle { get; set; }
        public string RegistrationNo { get; set; }
        public string Date { get; set; }
    
        public virtual Authentication Authentication { get; set; }
    }
}
