//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int ID { get; set; }
        public string Room { get; set; }
        public string Time { get; set; }
        public int SeatNo { get; set; }
        public string Paper { get; set; }
        public string RegistrationNo { get; set; }
    }
}
